// src/data/coursesData.js
const courses = [
    {
      id: 1,
      title: "React.js Beginner Course",
      instructor: "John Doe",
      price: "Rs 39.99",
      imageUrl: "https://i.ytimg.com/vi/922u1bkvER8/maxresdefault.jpg",
      instructorImage: "https://randomuser.me/api/portraits/men/1.jpg",
      level: "Beginner",
    },
    {
      id: 2,
      title: "Mastering JavaScript",
      instructor: "Jane Smith",
      price: "Rs 49.99",
      imageUrl: "https://www.squash.io/wp-content/uploads/2023/11/javascript-series.jpg",
      instructorImage: "https://randomuser.me/api/portraits/women/2.jpg",
      level: "Advanced",
    },
    {
      id: 3,
      title: "Full-Stack Web Development",
      instructor: "Alex Johnson",
      price: "Rs 79.99",
      imageUrl: "https://images.yourstory.com/cs/1/6b460cd040d711e994bbefffe3577d8b/full-stack-web-development-1586433444650.png?w=1152&fm=auto&ar=2:1&mode=crop&crop=faces",
      instructorImage: "https://randomuser.me/api/portraits/men/3.jpg",
      level: "Intermediate",
    },
    {
      id: 4,
      title: "MongoDB for Beginners",
      instructor: "Emily Davis",
      price: "Rs 29.99",
      imageUrl: "https://intellipaat.com/wp-content/uploads/2015/08/MongoDB-tutorial-for-Beginners.png",
      instructorImage: "https://randomuser.me/api/portraits/women/4.jpg",
      level: "Beginner",
    },
    {
      id: 5,
      title: "Node.js API Development",
      instructor: "Michael Brown",
      price: "Rs 59.99",
      imageUrl: "https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/311576405/original/73199ed4bbcfdc1c8941cc60600f4b769705a187/build-powerful-and-scalable-apis-using-nodejs.png",
      instructorImage: "https://randomuser.me/api/portraits/men/5.jpg",
      level: "Advanced",
    },
    {
      id: 6,
      title: "AWS Lambda Essentials",
      instructor: "Sophia Wilson",
      price: "Rs 69.99",
      imageUrl: "https://2.bp.blogspot.com/-exCOK8IeovE/WYmIV_GJ3UI/AAAAAAAAHWs/RKgqenhsXN8t99UzE-UU-swPYjXuMDXewCLcBGAs/s1600/03%2BAWS%2BLambda.png",
      instructorImage: "https://randomuser.me/api/portraits/women/6.jpg",
      level: "Intermediate",
    },
    {
      id: 7,
      title: "Python for Data Science",
      instructor: "Daniel Martinez",
      price: "Rs 99.99",
      imageUrl: "https://th.bing.com/th/id/OIP.JF5LAyPzzwgiCe_AjKH7IgHaD4?rs=1&pid=ImgDetMain",
      instructorImage: "https://randomuser.me/api/portraits/men/7.jpg",
      level: "Advanced",
    },
    {
      id: 8,
      title: "Machine Learning Basics",
      instructor: "Emma Thompson",
      price: "Rs 89.99",
      imageUrl: "https://buffml.com/wp-content/uploads/2022/12/machine_learning_basics.png",
      instructorImage: "https://randomuser.me/api/portraits/women/8.jpg",
      level: "Beginner",
    },
    {
      id: 9,
      title: "Next.js Crash Course",
      instructor: "Liam Anderson",
      price: "Rs 45.99",
      imageUrl: "https://i.ytimg.com/vi/mmn9fkRq3y0/maxresdefault.jpg",
      instructorImage: "https://randomuser.me/api/portraits/men/9.jpg",
      level: "Intermediate",
    },
    {
      id: 10,
      title: "Vue.js Fundamentals",
      instructor: "Olivia Hernandez",
      price: "Rs 55.99",
      imageUrl: "https://th.bing.com/th/id/OIP.F4lSzVuOHUYhD2a96NrzJAHaES?rs=1&pid=ImgDetMain",
      instructorImage: "https://randomuser.me/api/portraits/women/10.jpg",
      level: "Beginner",
    },
    {
      id: 11,
      title: "Docker & Kubernetes",
      instructor: "Noah Roberts",
      price: "Rs 79.99",
      imageUrl: "https://th.bing.com/th/id/OIP.trEa7VK9zToyRGTp4msGqwHaEK?rs=1&pid=ImgDetMain",
      instructorImage: "https://randomuser.me/api/portraits/men/11.jpg",
      level: "Advanced",
    },
    {
      id: 12,
      title: "Blockchain Development",
      instructor: "Sophia Garcia",
      price: "Rs 99.99",
      imageUrl: "https://4irelabs.com/wp-content/uploads/2020/11/blockchain-development-1024x646.png",
      instructorImage: "https://randomuser.me/api/portraits/women/12.jpg",
      level: "Intermediate",
    },
    {
      id: 13,
      title: "Ethical Hacking Bootcamp",
      instructor: "William King",
      price: "Rs 89.99",
      imageUrl: "https://miro.medium.com/v2/resize:fit:1200/1*vF1qMBjU8W2VPcKFCVcy-w.png",
      instructorImage: "https://randomuser.me/api/portraits/men/13.jpg",
      level: "Advanced",
    },
    {
      id: 14,
      title: "Cybersecurity Essentials",
      instructor: "Isabella Scott",
      price: "Rs 69.99",
      imageUrl: "https://th.bing.com/th/id/OIP.4JkciQs4DK6e99Z8Ym7EpAHaEv?rs=1&pid=ImgDetMain",
      instructorImage: "https://randomuser.me/api/portraits/women/14.jpg",
      level: "Beginner",
    },
    {
      id: 15,
      title: "Data Structures & Algorithms",
      instructor: "James Carter",
      price: "Rs 49.99",
      imageUrl: "https://miro.medium.com/v2/resize:fit:1200/1*-EFdnPuVrwUOmYte11v0OA.png",
      instructorImage: "https://randomuser.me/api/portraits/men/15.jpg",
      level: "Advanced",
    },
    {
      id: 16,
      title: "UI/UX Design Basics",
      instructor: "Charlotte Miller",
      price: "Rs 59.99",
      imageUrl: "https://enozom.com/wp-content/uploads/2024/04/mobile-app-design-fundamentals-the-difference-between-UI-and-UX.webp",
      instructorImage: "https://randomuser.me/api/portraits/women/16.jpg",
      level: "Intermediate",
    },
    {
      id: 17,
      title: "Android App Development",
      instructor: "Benjamin White",
      price: "Rs 79.99",
      imageUrl: "https://webclues-static.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2016/11/android_app_development-2.jpg",
      instructorImage: "https://randomuser.me/api/portraits/men/17.jpg",
      level: "Beginner",
    },
    {
      id: 18,
      title: "iOS App Development",
      instructor: "Mia Lewis",
      price: "Rs 89.99",
      imageUrl: "https://th.bing.com/th/id/OIP.G2VWpx56nB_SsprtY-vhGAHaES?rs=1&pid=ImgDetMain",
      instructorImage: "https://randomuser.me/api/portraits/women/18.jpg",
      level: "Intermediate",
    },
    {
      id: 19,
      title: "Game Development with Unity",
      instructor: "Ethan Walker",
      price: "Rs 99.99",
      imageUrl: "https://th.bing.com/th/id/OIP.DUknU0wVFwUcybFF8PAETAHaEK?rs=1&pid=ImgDetMain",
      instructorImage: "https://randomuser.me/api/portraits/men/19.jpg",
      level: "Advanced",
    },
    {
      id: 20,
      title: "Cloud Computing with AWS",
      instructor: "Ava Hall",
      price: "Rs 69.99",
      imageUrl: "https://cdn.img.gen.in/assets/Business/5806/Feeds/4653/5806_637348928825650620.jpg?rendered=true",
      instructorImage: "https://randomuser.me/api/portraits/women/20.jpg",
      level: "Intermediate",
    },
  ];
  
  export default courses;
  